### ISSUE TITLE
Include this behavior into nodenv core

### ISSUE THREAD

**Issue by therealparmesh** [nodenv/nodenv-package-rehash#13] opened 2017-09-06 19:30 UTC
It appears that [the inspiration for this plugin] (https://github.com/rbenv/rbenv-gem-rehash) has been deprecated in favor of implementing it as default behavior.

I'm not so sure this is actually working at the moment, so this may be a good opportunity to merge into the `nodenv` core.

I'm curious as to what you think about this idea. Thank you!

**Comment by jasonkarns** [comment] 2017-09-06 19:58
dupe of #8

**Closed by jasonkarns** 2017-09-06 19:58 UTC
